// <auto-generated />
using Bs.CheckApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bs.CheckApp.Persistence.Migrations
{
    [DbContext(typeof(ChequeDbContext))]
    [Migration("20220929010245_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Bs.CheckApp.Domain.Models.Cheque", b =>
                {
                    b.Property<string>("CheckNumber")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("ChequeBookNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCrossed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("CheckNumber");

                    b.ToTable("cheque");
                });
#pragma warning restore 612, 618
        }
    }
}
