// <auto-generated />
using Bs.CheckApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bs.CheckApp.Persistence.Migrations
{
    [DbContext(typeof(ChequeDbContext))]
    [Migration("20220929014558_init3")]
    partial class init3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Bs.CheckApp.Domain.Models.Cheque", b =>
                {
                    b.Property<string>("CheckNumber")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("ChequeBookNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endorsement")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCrossed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayeeLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayeeLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("CheckNumber");

                    b.ToTable("cheque");
                });

            modelBuilder.Entity("Bs.CheckApp.Domain.Models.ChequeBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChequeCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Complete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstChequeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeadingZeros")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCheque")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("cheque_book");
                });
#pragma warning restore 612, 618
        }
    }
}
